apiVersion: v1
kind: Service
metadata:
  name: ngmon-service
  namespace: develop
  labels:
    app: innovate
spec:
  ports:
  - name: ngmon
    port: 9113
    targetPort: 9113
    protocol: TCP
  selector:
    app: innovate
  type: ClusterIP
