apiVersion: apps/v1
kind: Deployment
# Opis deploymentu, nepovine udaje
metadata:
  name: innovate
  # namespave: myapp
# annotation su nepovine udaje pouzite na popis deploymentu,k tore ale niesu pouzite ako identifikatory pri query
  annotations:
    description: My training app
    release: "1.0"
spec:
  replicas: 4
# Selector sluzi na prepojenie servicov s deploymentami
  selector:
    matchLabels:
      app: innovate
  template:
    metadata:
      labels:
# Labels  - Identifying metadata that you can use to sort and select sets of API objects. Labels have many applications, including the following:
# SLuzia na identifikaciu objektov v API calloch
# kubectl get deployments --selector=app=innovate
        app: innovate
      annotations:
          version: "1.0"
          maintainer: Stefan Monko
    spec:
      containers:
      - name: innovate
        image: fsaregistrymonkos.azurecr.io/monko-cicd.northeurope.azurecontainer.io/innovate:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
